"""initial schema"""
from alembic import op
import sqlalchemy as sa

revision = '0b1c21797571'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pdf_files',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('content', sa.LargeBinary(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('bulletins',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('bo_number', sa.String(length=100), nullable=False),
    sa.Column('bulletin_type', sa.String(length=20), nullable=False),
    sa.Column('recipient_email', sa.String(length=254), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('pdf_storage_key', sa.String(length=100), nullable=True),
    sa.Column('pdf_generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('recipient_email_status', sa.String(length=20), nullable=False),
    sa.Column('battalion_email_status', sa.String(length=20), nullable=False),
    sa.Column('recipient_email_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('battalion_email_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bo_number')
    )
    op.create_index(op.f('ix_bulletins_created_by'), 'bulletins', ['created_by'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('bulletin_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('result', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['bulletin_id'], ['bulletins.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_table('people_involved',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('bulletin_id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['bulletin_id'], ['bulletins.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bulletin_id', 'position')
    )
    op.create_index(op.f('ix_people_involved_bulletin_id'), 'people_involved', ['bulletin_id'], unique=False)
    op.create_table('police_teams',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('bulletin_id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['bulletin_id'], ['bulletins.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_police_teams_bulletin_id'), 'police_teams', ['bulletin_id'], unique=False)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_police_teams_bulletin_id'), table_name='police_teams')
    op.drop_table('police_teams')
    op.drop_index(op.f('ix_people_involved_bulletin_id'), table_name='people_involved')
    op.drop_table('people_involved')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_bulletins_created_by'), table_name='bulletins')
    op.drop_table('bulletins')
    op.drop_table('users')
    op.drop_table('pdf_files')
    # ### end Alembic commands ###
